### ISSUE TITLE
Wiki syntax not displayed in datatable nor datalist

### ISSUE THREAD

**Issue by regystro** [splitbrain/dokuwiki-plugin-data#153]
While there's a way to include wiki syntax in dataentry:

	---- dataentry test ----
	description_wiki	: **Bold text**
	----

Once displayed as datatable or datalist, you get this:

`**Bold text**` instead of what you get when you visit the dataentry page: **Bold text**

Is there any way to force wiki syntax display in datatable / datalist?

Thank you.

**Comment by splitbrain** [comment]
What's your syntax for the datalist?

**Comment by regystro** [comment]
---- dataentry test ----
    description_wiki    : **Bold text** Normal text\\ Line 1\\ Line 2
    ----

Here's the page screenshot:
![image](https://cloud.githubusercontent.com/assets/5755481/6143953/3d331b6a-b1d1-11e4-8c17-3f4c07802814.png)

    ---- datatable ----
    cols    : description
    ----

    ---- datalist ----
    cols    : description
    ----

That's what I get:
![image](https://cloud.githubusercontent.com/assets/5755481/6143960/495e887a-b1d1-11e4-868d-5aa01327cf26.png)

I had 3 table related plugins installed but they are all disabled right now. I disabled all non-core plugins indeed.

**DokuWiki Version:** Release 2014-09-29b "Hrun"
**Structured data plugin version:** 2015-01-04

**Comment by splitbrain** [comment]
use this instead:

```
---- datalist ----
cols    : description_wiki
----
```

**Comment by regystro** [comment]
My bad. Totally missed this documentation paragraph:

> Like the dataentry, the values in the columns can also be formatted by postfixing the column names with the typealias. Like the deadline_dt column above. Another example shows website, as an url is given label the entries in cols with e.g. _url to enable linking in output.

I had a newbie's focusing problem: my dataentry was previously defined, then I discovered the _wiki formatting option but I forgot to add it to the datalist. Thanks man!!

BTW: great and very useful plugin :+1:
