### ISSUE TITLE
pageid doesn't link to data entry page anymore

### ISSUE THREAD

**Issue by selfthinker** [splitbrain/dokuwiki-plugin-data#173]
Having a `foo_pageid` in the data entry used to link to the page of the entry itself. This doesn't work anymore, instead it has a link to `foo`.

E.g. on the page staff:john I have the entry `Name_pageid: John Smith`. That used to link to `staff:john` but now it links to `staff:john_smith`.

**Comment by splitbrain** [comment]
That must have been a bug before. _pageid was never meant to refer to the page it is used on. Types specify the type of the entry. It correctly takes your input "John Smith" and turns it into a page id.
