### ISSUE TITLE
Blank pages after update of data plugin to 2016-03-11 10:33

### ISSUE THREAD

**Issue by tmo26** [splitbrain/dokuwiki-plugin-data#191]
After update of the data plugin to version 2016-03-11 10:33, the whole wiki shows only blank white pages.

Experienced this issue on two different wikis immediately after the update to the mentioned version.

**Comment by tmo26** [comment]
Manual installation of https://github.com/splitbrain/dokuwiki-plugin-data/tree/29897f2c169bde1ceab1bd10ef34204da6afbb33 solves the problem, wiki working again as expected.

**Comment by splitbrain** [comment]
Blank page sounds like a fatal error. I need the exact error message to debug this. Please refer to https://www.dokuwiki.org/faq:blankpage

**Comment by tmo26** [comment]
- On my demowiki: No error shown in
/var/log/messages
/var/log/syslog
/var/log/nginx/dokuwiki-error.log
/var/log/php5-fpm.log

- php.ini:
log_errors = On
error_log = syslog
- php_blenc.dll + php_operator.dll are not present in php.ini
- Adding &purge=true to the URL does not solve the problem
- findbadphp.php:
```
starting...
/var/www/demowiki/bin/wantedpages.php doesn't start with <?php
/var/www/demowiki/bin/striplangs.php doesn't start with <?php
/var/www/demowiki/bin/render.php doesn't start with <?php
/var/www/demowiki/bin/gittool.php doesn't start with <?php
/var/www/demowiki/bin/indexer.php doesn't start with <?php
/var/www/demowiki/bin/dwpage.php doesn't start with <?php
/var/www/demowiki/conf/acl.auth.php doesn't start with <?php
/var/www/demowiki/conf/users.auth.php doesn't start with <?php
/var/www/demowiki/lib/images/fileicons/index.php doesn't start with <?php
/var/www/demowiki/lib/images/smileys/index.php doesn't start with <?php
/var/www/demowiki/lib/plugins/pagelist/lang/ar/lang.php has UTF-8 BOM at start.
/var/www/demowiki/lib/plugins/pagelist/lang/ar/settings.php has UTF-8 BOM at start.
finished...
```

**Comment by splitbrain** [comment]
The only change made between the releases is the renaming of a constructor. That should be unproblematic unless something calls that constructor directly by it's name instead of just calling new on the class name. I don't see something like this in the data plugin itself, so it could only happen when a different plugin makes use of the data plugin. Since I have no idea what plugin that might be I can't debug.

A blank page should produce  an error log somewhere. Can you check phpinfo() to see if logs are actually written to syslog?

**Comment by tmo26** [comment]
> I don't see something like this in the data plugin itself, so it could only happen when a different plugin makes use of the data plugin.

That was a good hint: I disabled the "Data Template Plugin" (https://www.dokuwiki.org/plugin:datatemplate) and the update of the Data plugin went without errors.

-> The Data Template plugin is the culprit!
