### ISSUE TITLE
git tags missing

### ISSUE THREAD

**Issue by glensc** [splitbrain/dokuwiki-plugin-data#206]
please create and push git tags when making release (updating version in `plugin.info.txt`)

currently none present:
https://github.com/splitbrain/dokuwiki-plugin-data/releases

ps: think of automating that with travis-ci, for example travis creates and pushes  tag when plugin.info.txt version is updated.

**Comment by splitbrain** [comment]
I'd like to add this feature into this script when I have time: https://gist.github.com/splitbrain/a002268d74189c758b7e

**Comment by glensc** [comment]
wow. you say you have no time and write such script. wow :D

**Comment by glensc** [comment]
i see newer tags now: https://github.com/splitbrain/dokuwiki-plugin-data/releases

closing then
