### ISSUE TITLE
How many datatables are allowed per page

### ISSUE THREAD

**Issue by Wolfgang1234** [splitbrain/dokuwiki-plugin-data#226]
We have 19 datatables on one page. This is working well.
But when we add the 20th datatable to our page and save it,
we receive an blank page as result. 

An simple question, is there an limit on datatables allowed at one page ?

`---- datatable ----`
`cols    : %pageid%`
`headers : Details`
`filter  : customer_page=`
`----`

**Comment by Wolfgang1234** [comment]
I found my answer in the Structured Data Plugin Documentation. Seems like it is limited to 19 data-structures per page.

**Comment by Wolfgang1234** [comment]
I found my answer in the Structured Data Plugin Documentation. Seems like it is limited to 19 data-structures per page.

**Comment by splitbrain** [comment]
what? where exactly did you find that?

I don't think there's any limit. A white page is most likely a fatal error like an out of memory error. check your logs.

**Comment by Wolfgang1234** [comment]
I had an look at the Structured Data Plugin Page. 
https://www.dokuwiki.org/plugin:data#missing_features

Here is written:

More data-entry blocks at one page. Reason: the Data Plugin is designed as data-entry block per page. ⇒ Recommended alternative: [Strata Plugin](https://www.dokuwiki.org/plugin:strata), which is equivalent to Data plugin, but bit more sophisticated.

Maybe I wrongly understand this, but for me it sounds like there is an limit.

**Comment by splitbrain** [comment]
then report your problem at the adapter plugin's bug tracker.

**Comment by splitbrain** [comment]
sorry. commented on the wrong issue first...

There are no programmatical limits in the data plugin. Check your error logs.

**Comment by Wolfgang1234** [comment]
thanks for your advice
For the moment I will split our page in 2 subpages, to avoid this problem. 
But the Dokuwiki is growing, this means I need to analyze this problem.
I close this ticket for the moment. If I find the problem I will post is here.
