### ISSUE TITLE
Struct Aggregation tables put a space in the middle of numbers before or after thousands separator

### ISSUE THREAD

**Issue by craigdrown** [splitbrain/dokuwiki-plugin-data#248]
It's actually a U+202F character.
Makes export to Excel etc not recognize the value as a number.
Before the separator if the column is right-aligned, after the separator if left-aligned (or centered):

![CleanShot 2024-11-07 at 08 41 23](https://github.com/user-attachments/assets/10752996-5f97-4cdc-824c-296a44246ce7)

**Comment by splitbrain** [comment]
you talk about struct but this is the data plugin repo. which one is it?

**Comment by craigdrown** [comment]
Dang- wrong repo, sorry! Have re-submiited
