### ISSUE TITLE
Tag filtering when column ends with an 's' example Ingredients_tags

### ISSUE THREAD

**Issue by lenzenmi** [splitbrain/dokuwiki-plugin-data#59]
For data tags with a column that ends in an 's' like "Ingredients_tags".

When you click on the displayed tag, it will open the correct page, however data filtering shows no results.

Filtering works fine for a column named "Ingredient_tags" without the 's'

**Comment by bitozoid** [comment]
Happening to me with version 2013-10-09. Upgraded to latest (2015-01-04) and still happening. I can't replace code in `helper.php` from previous commit:

```php
284                     $outs[] = '<a href="' . wl(str_replace('/', ':', cleanID($target)), $this->_getTagUrlparam($column, $val))
285                         . '" title="' . sprintf($this->getLang('tagfilter'), hsc($val))
286                         . '" class="wikilink1">' . hsc($val) . '</a>';
```

**Comment by stvoigt** [comment]
Ich kehre zurück am 09.02.2015.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten. Herzlichen Dank
für ihr Verständnis.

I will answer your message after returning.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[dokuwiki-plugin-data] Tag filtering when column ends with an 's' example
Ingredients_tags (#59)" gesendet am 02.02.2015 15:25:42.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.=
